baseURL = 'https://colby.gg'
languageCode = 'en-us'
title = 'colby.gg'
theme = 'github.com/vaga/hugo-theme-m10c'

[params]
    author = "Jon Colby"
    featured_image = "/images/banner.png"
    Description = "Some guy who does stuff and things"
    avatar = "images/banner.png"
[[params.social]]
    icon = "brand-github"
    name = "github"
    url = "https://github.com/MrUsefull"
[[params.social]]
    icon = "brand-linked"
    name = "linkedin"
    url = "https://www.linkedin.com/in/jonathan-colby-a9198b99/"

[related]
  threshold = 20
  includeNewer = true
  [related.indices]
    applyFilter = true
    name = "tags"
    weight = 100

[taxonomies]
  tag = "tags"
  series = "series"